/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_portonvictor_errno_Errno */

#ifndef _Included_org_portonvictor_errno_Errno
#define _Included_org_portonvictor_errno_Errno
#ifdef __cplusplus
extern "C" {
#endif
#undef org_portonvictor_errno_Errno_serialVersionUID
#define org_portonvictor_errno_Errno_serialVersionUID -3042686055658047285LL
#undef org_portonvictor_errno_Errno_serialVersionUID
#define org_portonvictor_errno_Errno_serialVersionUID 4980196508277280342LL

JNIEXPORT jbyteArray JNICALL Java_org_portonvictor_errno_Errno_getMessageImpl
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_org_portonvictor_errno_Errno_getErrno
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
